server:
  port: 8086

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: nacos-test2
          uri: lb://nacos-client
          predicates:
            - Path=/test2/**
      filter:
        strip-prefix:
          enabled: true

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
